# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff8247b4a9375d2810256ab3f3825ef85bbd06ad9e6c9826e59e59161c8ec86248b8e5850a1e9c3b5478db2486714f8420325dcf8fe0d0366c47b5d51998bd36

test:
  secret_key_base: 0a0ae89a7efea451cba78b31dfae65b1df379d4fdb3f349b2fdd6a6c94ed648ea1664f119b89a79d19c910c5fc3cf3909ef4bb2938b40d4d8943dc9b98b734f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
